const promociones = [
    {"Titulo": "Básico", "Precio":"120$/mes",
     "List1":"Entrega a domicilio",
     "List2":"Tacos 2x1",
     "List3":"Un cupon Gratis",
     "List4":"Un postre Gratis"},
     {"Titulo": "Pro", "Precio":"250$/mes",
     "List1":"Entrega a domicilio",
     "List2":"Cerveza 2x1",
     "List3":"Bebidas gratis",
     "List4":"Un postre Gratis"},
     {"Titulo": "Premium", "Precio":"500$/mes",
     "List1":"Entrega a domicilio",
     "List2":"Orden de tacos gratis",
     "List3":"Postres y bebidas gratis",
     "List4":"Dos postres Gratis"},
]
const promociones2 = [
    {"Titulo2":"Básico","Precio2":"500$/mes",
    "Listt1":"Entrega a domicilio",
    "Listt2":"Postres Gratis",
    "Listt3":"Bebidas Gratis",
    "Listt4":"2x1 en Tacos"},
    {"Titulo2":"Pro","Precio2":"800$/mes",
    "Listt1":"Entrega a domicilio",
    "Listt2":"Postres y bebidas gratis",
    "Listt3":"Bebidas Gratis",
    "Listt4":"2x1 en Cerveza"},
    {"Titulo2":"Premium","Precio2":"1000$/mes",
    "Listt1":"Entrega a domicilio",
    "Listt2":"Postres y bebidas gratis",
    "Listt3":"Bebidas Gratis",
    "Listt4":"3x1 en Cerveza"},
]

export {promociones,promociones2};